
# html lang
language: zh-Hans

# main menu navigation
menu:
  home: /
  archives: /archives
  tags: /tags
  #categories: /categories
  search: /search
  about: localhost
  rss: /atom.xml

search:
  path: search.xml
  field: post
  content: true
  format: html


feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content_limit: 140
  
sitemap:
    path: sitemap.xml



# Miscelaneous
favicon: /logo.png

# stylesheets loaded in the <head>
stylesheets:
# - /css/normalize.css
- //cdn.bootcss.com/pure/1.0.0/pure-min.css
- /css/xoxo.css

# scripts loaded in the end of the body
scripts:
#- //cdn.bootcss.com/zepto/1.2.0/zepto.min.js
#- /js/xoxo.js

# switch
show_excerpt: true
show_date: true
#footer
index_page: https://blog.0xff000000.com
main_site: https://0xff000000.com
github: https://github.com/KevinOfNeu


# 阅读时间计算配置
wordcount:
  # 中文每分钟阅读字数
  cn: 300
  # 英文每分钟阅读单词数
  en: 160